style(clippy): stop using single component path imports
This is I think only available on nightly clippy, so it's failing on
stable (in CI).

```
error: unknown clippy lint: clippy::single_component_path_imports
  --> src/main.rs:26:5
   |
26 |     clippy::single_component_path_imports,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::unknown-clippy-lints` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unknown_clippy_lints
```